server {
    root www/;
    listen localhost:8080;
    listen localhost:9090;
    server_name example.com;
    client_max_body_size 1M;
    error_page 404 www/html/errors/default.html;
    error_page 500 /errors/50x.html;

    location / {
        autoindex off;
        methods GET POST DELETE HEAD;
    }

    location /teste {
        root www/html/teste;
    }

    location /upload {
        methods POST DELETE;
        upload_dir www/uploads;
    }

    location /cgi-bin {
        methods GET POST;
        root /www/cgi-bin;
        cgi_ext .py /usr/bin/python3;
        cgi_ext .php /usr/bin/php-cgi;
    }
}