server {
    root www/;
    listen localhost:8080;
    server_name example.com;
    client_max_body_size 1M;
    error_page 403 www/html/errors/default.html;
    error_page 404 www/html/errors/default.html;
    error_page 405 www/html/errors/default.html;
    error_page 408 www/html/errors/default.html;
    error_page 413 www/html/errors/default.html;
    error_page 414 www/html/errors/default.html;
    error_page 431 www/html/errors/default.html;
    error_page 500 www/html/errors/default.html;
    error_page 501 www/html/errors/default.html;
    error_page 503 www/html/errors/default.html;

    location / {
        methods GET;
    }

    location /post_body {
        methods POST;
        client_max_body_size 100M;
    }

    location /uploads/ {
        autoindex on;
        methods DELETE POST GET;
        root www/uploads/;
        upload_dir www/uploads/;
        index .keep;
    }

    location /directory/ {
        methods GET;
        root YoupiBanane/;
        index youpi.bad_extension;
    }

    location /cgi-bin {
        methods GET POST;
        root /www/cgi-bin;
        cgi_ext .py /usr/bin/python3;
    }

    location /no-method {
        methods POST;
        root www/html/no-method/;
    }
}

server {
    root www/;
    listen localhost:9090;
    server_name example.com;
    client_max_body_size 1M;
    error_page 403 www/html/errors/default.html;
    error_page 404 www/html/errors/default.html;
    error_page 405 www/html/errors/default.html;
    error_page 408 www/html/errors/default.html;
    error_page 413 www/html/errors/default.html;
    error_page 414 www/html/errors/default.html;
    error_page 431 www/html/errors/default.html;
    error_page 500 www/html/errors/default.html;
    error_page 501 www/html/errors/default.html;
    error_page 503 www/html/errors/default.html;

    location / {
        methods GET;
    }

    location /post_body {
        methods POST;
        client_max_body_size 100M;
    }

    location /uploads/ {
        autoindex on;
        methods DELETE POST GET;
        root www/uploads/;
        upload_dir www/uploads/;
        index .keep;
    }

    location /directory/ {
        methods GET;
        root YoupiBanane/;
        index youpi.bad_extension;
    }

    location /cgi-bin {
        methods GET POST;
        root /www/cgi-bin;
        cgi_ext .py /usr/bin/python3;
    }

    location /no-method {
        methods POST;
        root www/html/no-method/;
    }
}
