# ============================================================================
# Webserv - default_config_v1.conf
# ============================================================================
#
# Decisões de Design do config system:
#
# - São permitidos múltiplos blocos `server`.
# - Cada bloco `server` pode ter múltiplas diretivas `listen`.
# - A diretiva `server_name` é opcional.
# - Caso múltiplos servidores escutem na mesma porta e nenhum `server_name`
#   corresponda ao Host da request, é utilizado o primeiro servidor declarado.
# - Os blocos `location` não são obrigatórios.
# - Caso nenhuma `location` corresponda ao pedido, aplica-se o comportamento
#   default do `server` (usar o root definido no `server`).
# - A correspondência das diretivas `location` segue a regra do longest-prefix
#   (estilo NGINX).
# - Uma `location` pode sobrepor (override) o `root` definido no `server`.
# - A diretiva `methods` é opcional e, se não for definida, todos os métodos
#   suportados são permitidos por defeito.
#
# ============================================================================

# ----------------------------------------------------------------------------
# Exemplo 1:
# Servidor a correr nas portas 9000 e 9001.
# Sem blocos location definidos.
# Todos os ficheiros são servidos a partir do directorio root definido.
# ----------------------------------------------------------------------------

server {
    listen 9000;
    listen 9001;

    server_name WebServ;

    root /var/www/html;
}

# ----------------------------------------------------------------------------
# Exemplo 2:
# Servidor a correr na porta 9090.
#
# Root defaultt: /var/www/html
#
# Se o path da request começar por /images, aplica-se override ao root e os ficheiros são servidos a partir de /data/images.
#
# Exemplo:
#   Request:  GET /images/coiso.png
#   Ficheiro servido: /data/srcs/content/images/coiso.png
# ----------------------------------------------------------------------------

server {
    listen 9090;

    server_name WebServ2;

    root /var/www/html2;

    location /images {
        root /data/srcs/content/images;
    }
}