server {
    listen 127.0.0.1:8080;
    root www;
    location /upload/ {
        upload_dir www/uploads;
        methods POST DELETE;
        client_max_body_size 10240;
    }
    location /forbidden/ {
        upload_dir www/uploads/forbidden;
        methods POST DELETE;
        client_max_body_size 10240;
    }
}