server {
    root www/;
    listen localhost:9090;
    server_name localhost;
    client_max_body_size 200M;

    location / {
        methods GET;
        autoindex off;
        index index.html;
    }

    location /post_body {
        methods POST GET DELETE;
        client_max_body_size 100M;
    }

    location /directory {
        methods GET POST;
        root YoupiBanane;
        autoindex off;
        index youpi.bad_extension;
        cgi_ext .bla ./cgi_tester;
    }
}
