# global comment

server {
    listen 8080;
    root /var/www;

    server_name example.com localhost;

    methods GET POST;

    client_max_body_size 5M;

    error_page 404 /errors/404.html;



    location /images {
        root /data/images;
        autoindex on;
        methods GET;
        cgi_ext .php /usr/bin/php-cgi;
    }
}

server {
    listen 8080;
    server_name site1.com;
    root /bin/www;
}

server {
    listen 8080;
    root /etc/www;
    server_name site2.com;
}

server {
    listen 9090;
    root /etc/www;
    server_name site2.com;
}