server {
    listen 8080;
    root /var/www;
    server_name site1.com;
    methods GET POST;
    client_max_body_size 5M;

    location / {
        root /var/www;
        methods GET;
    }
}

server {
    listen 9090;
    root /var/www2;
    server_name site2.com;
    methods GET POST;
    client_max_body_size 2M;

    location / {
        root /var/www2;
        methods GET;
    }
}
